name: Password generator

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Setup module
      run: |
        npm install -g html-minifier
        npm install -g uglify-js
        npm install -g clean-css-cli

    - name: Make directory
      run: |
        mkdir -p ./dist

    - name: HTML minifier
      run: |
        html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype ./index.html -o ./dist/index.html

    - name: JS minifier
      run: |
        uglifyjs ./pwdgen.js -c -m --output ./dist/pwdgen.js
        uglifyjs ./index.js -c -m --output ./dist/index.js

    - name: CSS minifier
      run: |
        cleancss -o ./dist/pwdgen.css ./pwdgen.css

    - name: Resources cory
      run: |
        cp ./favicon.ico ./dist/

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
